project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "projects/*.qmd"
    - "!about.qmd"

metadata:
  keywords:
    - "spiking neural network"
    - "PhD TU Wien"
    - "NeuroAI"
    - "Connectivity"
    - "Computational neurosciences"


website:
  title: "Laurine Marty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <meta name="google-site-verification" content="Ck7euak3bY43uBUd2WAdoWP_7flkF4U42f5TsR69Zwg" />




